# Generated by Django 2.2.1 on 2019-05-11 18:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import masters.apps.courses.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Title')),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, unique=True, verbose_name='Slug')),
                ('abstract', models.TextField(blank=True, max_length=2048, verbose_name='Abstract')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/', verbose_name='Thumbnail')),
                ('is_free', models.BooleanField(default=False, verbose_name='Is Free')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Price')),
                ('time_duration', models.CharField(blank=True, max_length=100, verbose_name='Time Duration')),
                ('level', models.CharField(blank=True, max_length=100, verbose_name='Level')),
                ('suggested_to', models.TextField(blank=True, verbose_name='Suggested To')),
                ('published', models.BooleanField(default=False, verbose_name='Published')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Title')),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, unique=True, verbose_name='Slug')),
                ('weight', models.SmallIntegerField(blank=True, null=True, verbose_name='Weight')),
            ],
            options={
                'verbose_name': 'Course Category',
                'verbose_name_plural': 'Course Categories',
                'ordering': ['weight'],
            },
        ),
        migrations.CreateModel(
            name='CourseSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Title')),
                ('weight', models.SmallIntegerField(blank=True, null=True, verbose_name='Weight')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='Course')),
            ],
            options={
                'verbose_name': 'Course Section',
                'verbose_name_plural': 'Course Sections',
                'ordering': ['weight'],
            },
        ),
        migrations.CreateModel(
            name='CourseSectionItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, unique=True, verbose_name='Slug')),
                ('item_type', models.CharField(choices=[('video', 'Video')], default='video', max_length=255, verbose_name='Item Type')),
                ('is_free', models.BooleanField(default=False, verbose_name='Is Free')),
                ('public_url', models.CharField(blank=True, max_length=1024, verbose_name='Public Url')),
                ('duration', models.CharField(blank=True, max_length=128, verbose_name='Duration')),
                ('weight', models.SmallIntegerField(blank=True, null=True, verbose_name='Weight')),
                ('file_url', models.FileField(blank=True, null=True, upload_to=masters.apps.courses.utils.get_file_path, verbose_name='File')),
                ('published', models.BooleanField(default=True, verbose_name='Published')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.CourseSection', verbose_name='Course Sections')),
            ],
            options={
                'verbose_name': 'Course Section Item',
                'verbose_name_plural': 'Course Section Items',
                'ordering': ['weight'],
            },
        ),
        migrations.CreateModel(
            name='CourseKeyPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Title')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='Course')),
            ],
            options={
                'verbose_name': 'Course Key Point',
                'verbose_name_plural': 'Course Key Points',
            },
        ),
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enroll_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Enroll Date')),
                ('enroll_type', models.CharField(choices=[('manual', 'Manual')], default='manual', max_length=25, verbose_name='Enroll Type')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='Course')),
            ],
            options={
                'verbose_name': 'Course Enrollment',
                'verbose_name_plural': 'Course Enrollments',
                'ordering': ['-enroll_date'],
            },
        ),
    ]
