# Generated by Django 2.2.1 on 2019-05-12 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseenrollment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='course',
            name='authors',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='categories',
            field=models.ManyToManyField(to='courses.CourseCategory'),
        ),
        migrations.AddField(
            model_name='course',
            name='pre_requirements',
            field=models.ManyToManyField(blank=True, related_name='prereqs', to='courses.Course'),
        ),
        migrations.AlterUniqueTogether(
            name='courseenrollment',
            unique_together={('user', 'course')},
        ),
    ]
