# Generated by Django 2.2.1 on 2019-05-12 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20190512_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='in_progress',
            field=models.BooleanField(default=False, verbose_name='in progress'),
        ),
    ]
