# Generated by Django 2.2.1 on 2019-05-13 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_in_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesectionitem',
            name='need_enroll',
            field=models.BooleanField(default=True, verbose_name='need enrolled'),
        ),
    ]
